config/routes.rb
Rails.application.routes.draw do
  
  use_doorkeeper do
    # it accepts :authorizations, :tokens, :token_info, :applications and :authorized_applications
    #as :applications => 'custom_applications'
    controllers :applications => 'doorkeeper/custom_applications'
  end
  
  root to: "pages#root"
  get 'authentication/new'
  post 'authentication/create'
  #route per ritornare le info dell'ente da un client_id
  get '/oauth/application/get_info_cid/:cid', to: 'doorkeeper/custom_applications#get_info_cid', as: 'get_info_cid'

  get 'auth_mancante' => 'authentication#auth_mancante', :as => :auth_mancante
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doorkeeper/application.rb
module Doorkeeper
    class Application < ActiveRecord::Base
        
        # def as_json(options={})
        #     return self.attributes.as_json
        # end

        def as_json(options = {})
            super
        end

    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    
    
    
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  
  #form di login, ho parametro in sessione per redirect url e client id
  def new
    unless session[:client_id].blank?
      applicazione = Doorkeeper::Application.find_by uid: session[:client_id]
      if applicazione.blank?
        logger.error "\n\n Applicazione con client_id #{session[:client_id]} non presente!   \n"
        @errore = "Login non permesso!"
      else
        @nome_ente = applicazione.name
        @redirect_uri = applicazione.redirect_uri
        @image_url = applicazione.image_url
      end
    else
      @errore = "Login non permesso!"
    end
  
  end

  #arriva il post da form login react con csrf token
  #params['data']
  #{"stato"=>"ok", "sid_sessione"=>"3f3a597a-325c-40eb-81c2-544a0bee9d78", 
  #"dati_utente"=>{"nome"=>"Andrea", "cognome"=>"Grazian", "codice_fiscale"=>"BRRRRT68L71B300L", "id"=>1}, "servizi_privati"=>[]} 
  def create
    if params['data'].blank? || params['data']['dati_utente'].blank?
      msg = { :stato => "ko", :messaggio => "Dati Mancanti" }
    else
      #carico l'applicazione dal client_id in sessione
      app = Doorkeeper::Application.find_by(uid: session[:client_id])
      session['user'] = params['data']['dati_utente']
      session['user']['sid_sessione'] = params['data']['sid_sessione']
      session['user']['application_id'] = app.id unless app.blank?
      msg = { :stato => "ok", :messaggio => "Login Effettuato!" }
    end
    respond_to do |format|
      format.json  { render json: msg } 
    end
  end

     
  def auth_mancante
        
  end


end

app/controllers/doorkeeper/custom_applications_controller.rb
module Doorkeeper
    class CustomApplicationsController < ApplicationsController
        layout 'doorkeeper/admin' unless Doorkeeper.configuration.api_only
    
        #before_action :authenticate_admin!, only: [] #da abilitare in localhost
        before_action :authenticate_admin!, except: [:get_info_cid] #da abilitare in prod
        before_action :set_application, only: %i[show edit update destroy]
    
        #Controllo di avere un parametro jwt e di poterlo decodificare
        def authenticate_admin!
          jwt = params[:jwt] || session['auth']
          unless jwt.blank?
            begin
              hash_token_decoded = JsonWebToken.decode(jwt) 
              #verifico istante temporale
              unless JsonWebToken.valid_token(hash_token_decoded)
                redirect_to auth_mancante_path
              end
              session['auth'] = jwt
            rescue => exc
              logger.error "Oauth2: Problemi decodifica jwt per autenticazione: "+exc.message
              logger.error exc.backtrace.join("\n")
              redirect_to auth_mancante_path
            end
          else
            redirect_to auth_mancante_path
          end

        end


        def index
            if params['demo_mode'] == 'true'
              @applications = Application.where(demo_site: true).ordered_by(:created_at)
            else
              if request.format.to_s == "application/json" #caso app che mostra solo enti non di demo
                @applications = Application.where(demo_site: [nil, false]).ordered_by(:created_at)
              else #caso da web che vede tutti
                @applications = Application.all.ordered_by(:created_at)
              end
            end
            respond_to do |format|
                format.html
                format.json { render json: @applications }
            end
        end
    
        def show
          respond_to do |format|
            format.html
            format.json { render json: @application }
          end
        end
    
        def new
          @application = Application.new
        end
    
        def create
          @application = Application.new(application_params)
    
          if @application.save
            flash[:notice] = I18n.t(:notice, scope: %i[doorkeeper flash applications create])
    
            respond_to do |format|
              format.html { redirect_to oauth_application_url(@application) }
              format.json { render json: @application }
            end
          else
            respond_to do |format|
              format.html { render :new }
              format.json { render json: { errors: @application.errors.full_messages }, status: :unprocessable_entity }
            end
          end
        end
    
        def edit; end
    
        def update
          if @application.update(application_params)
            flash[:notice] = I18n.t(:notice, scope: %i[doorkeeper flash applications update])
    
            respond_to do |format|
              format.html { redirect_to oauth_application_url(@application) }
              format.json { render json: @application }
            end
          else
            respond_to do |format|
              format.html { render :edit }
              format.json { render json: { errors: @application.errors.full_messages }, status: :unprocessable_entity }
            end
          end
        end
    
        def destroy
          flash[:notice] = I18n.t(:notice, scope: %i[doorkeeper flash applications destroy]) if @application.destroy
    
          respond_to do |format|
            format.html { redirect_to oauth_applications_url }
            format.json { head :no_content }
          end
        end
    
        #ritorna le info dell'ente
        def get_info_cid
          hash_params = params.permit!
          app_ente_info = {}
          c_id = hash_params[:cid]
          qs_app_ente = Application.where(uid: c_id)
          unless qs_app_ente.blank?
            #popolo hash 
            app_ente = qs_app_ente[0]
            app_ente_info[:client_id] = c_id
            app_ente_info[:nome_ente] = app_ente.name
            app_ente_info[:url_ente] = app_ente.portal_url 
          end
          
          respond_to do |format|
            #format.html { render app_ente_info }
            format.json { render json: app_ente_info.to_json }
          end
          

        end


        private
    
        def set_application
          @application = Application.find(params[:id])
        end

        def application_params
          params.require(:doorkeeper_application).permit(:name, :redirect_uri, :scopes, :confidential, :image_url, :tipo_login, :portal_url, :extra_info, :demo_site, :mobile_app, :demo_mode)
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/views/authentication/auth_mancante.html.erb
<div id="no_auth">
<h3>AUTENTICAZIONE MANCANTE!</h3>
</div>

app/views/authentication/create.html.erb
<h1>Authentication#create</h1>
<p>Find me in app/views/authentication/create.html.erb</p>

app/views/authentication/new.html.erb
<div id="nuova_autenticazione">
    <span id="nome_ente" valore="<%=@nome_ente%>"></span>
    <span id="redirect_uri" valore="<%=@redirect_uri%>"></span>
    <div id="msg_errore" class="alert alert-danger <%= (@errore.blank? ? 'd-none' : '') %>"><%=@errore%></div>
    <div id="react_component"></div>
    
</div>

app/views/doorkeeper/applications/_delete_form.html.erb
<%- submit_btn_css ||= 'btn btn-link' %>
<%= form_tag oauth_application_path(application), method: :delete do %>
  <%= submit_tag t('doorkeeper.applications.buttons.destroy'),
                 onclick: "return confirm('#{ t('doorkeeper.applications.confirmations.destroy') }')",
                 class: submit_btn_css %>
<% end %>

app/views/doorkeeper/applications/_form.html.erb
<%= form_for application, url: doorkeeper_submit_path(application), html: { role: 'form' } do |f| %>
  <% if application.errors.any? %>
    <div class="alert alert-danger" data-alert><p><%= t('doorkeeper.applications.form.error') %></p></div>
  <% end %>

  <div class="form-group row">
    <%= f.label :name, class: 'col-sm-2 col-form-label font-weight-bold' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control #{ 'is-invalid' if application.errors[:name].present? }", required: true %>
      <%= doorkeeper_errors_for application, :name %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :portal_url, class: 'col-sm-2 col-form-label font-weight-bold' %>
    <div class="col-sm-10">
      <%= f.text_area :portal_url, class: "form-control #{ 'is-invalid' if application.errors[:portal_url].present? }" %>
      <%= doorkeeper_errors_for application, :portal_url %>
      <span class="form-text text-secondary">
        <%= t('doorkeeper.applications.help.portal_url') %>: Url della index del sito. (Es: https://dominio/portal/ )
      </span>
    </div>
  </div>
  
  <div class="form-group row">
    <%= f.label :redirect_uri, class: 'col-sm-2 col-form-label font-weight-bold' %>
    <div class="col-sm-10">
      <%= f.text_area :redirect_uri, class: "form-control #{ 'is-invalid' if application.errors[:redirect_uri].present? }" %>
      <%= doorkeeper_errors_for application, :redirect_uri %>
      <span class="form-text text-secondary">
        <%= t('doorkeeper.applications.help.redirect_uri') %>. Url di callback dopo Oauth2. (Es: https://dominio/portal/auth/oauth2/callback )
      </span>

      <% if Doorkeeper.configuration.native_redirect_uri %>
          <span class="form-text text-secondary">
            <%= raw t('doorkeeper.applications.help.native_redirect_uri', native_redirect_uri: content_tag(:code, class: 'bg-light') { Doorkeeper.configuration.native_redirect_uri }) %>
            
          </span>
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :confidential, class: 'col-sm-2 form-check-label font-weight-bold' %>
    <div class="col-sm-10">
      <%= f.check_box :confidential, class: "checkbox #{ 'is-invalid' if application.errors[:confidential].present? }" %>
      <%= doorkeeper_errors_for application, :confidential %>
      <span class="form-text text-secondary">
        <%= t('doorkeeper.applications.help.confidential') %>
      </span>
    </div>
  </div>
  
  <div class="form-group row">
    <%= f.label :demo_site, 'Ente per demo ?', class: 'col-sm-2 form-check-label font-weight-bold' %>
    <div class="col-sm-10">
      <%= f.check_box :demo_site, class: "checkbox #{ 'is-invalid' if application.errors[:demo_site].present? }" %>
      <%= doorkeeper_errors_for application, :demo_site %>
      <span class="form-text text-secondary">
        <%= t('doorkeeper.applications.help.demo_site') %>
      </span>
    </div>
  </div>
  
  <div class="form-group row">
    <%= f.label :mobile_app, 'Usa app nativa?', class: 'col-sm-2 form-check-label font-weight-bold' %>
    <div class="col-sm-10">
      <%= f.check_box :mobile_app, class: "checkbox #{ 'is-invalid' if application.errors[:mobile_app].present? }" %>
      <%= doorkeeper_errors_for application, :mobile_app %>
      <span class="form-text text-secondary">
        <%= t('doorkeeper.applications.help.mobile_app') %>
      </span>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :scopes, class: 'col-sm-2 col-form-label font-weight-bold' %>
    <div class="col-sm-10">
      <%= f.text_field :scopes, class: "form-control #{ 'has-error' if application.errors[:scopes].present? }" %>
      <%= doorkeeper_errors_for application, :scopes %>
      <span class="form-text text-secondary">
        <%= t('doorkeeper.applications.help.scopes') %>
      </span>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :image_url, class: 'col-sm-2 col-form-label font-weight-bold' %>
    <div class="col-sm-10">
      <%= f.text_field :image_url, class: "form-control #{ 'has-error' if application.errors[:image_url].present? }" %>
      <%= doorkeeper_errors_for application, :image_url %>
      <span class="form-text text-secondary">
        <%= t('doorkeeper.applications.help.image_url') %> Url dello stemma dell'ente. (Es: https://dominio/public/img/stemma.png )
      </span>
    </div>
  </div>
  
  <div class="form-group row">
    <%= f.label :tipo_login, class: 'col-sm-2 col-form-label font-weight-bold' %>
    <div class="col-sm-10">
      <!--- <%= f.text_field :tipo_login, class: "form-control #{ 'has-error' if application.errors[:tipo_login].present? }" %> -->
      <%= f.select(:tipo_login) do %>
        <% [['Front End', 1], ['API', 2]].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
      <% end %>
      
      <%= doorkeeper_errors_for application, :tipo_login %>
      <span class="form-text text-secondary">
        <%= t('doorkeeper.applications.help.tipo_login') %>
      </span>
    </div>
  </div>

  
  
  <div class="form-group row">
    <%= f.label :extra_info, class: 'col-sm-2 col-form-label font-weight-bold' %>
    <div class="col-sm-10">
      <%= f.text_area(:extra_info, size: '50x5') %>
      
      <%= doorkeeper_errors_for application, :extra_info %>
      
    </div>
  </div>
  


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit t('doorkeeper.applications.buttons.submit'), class: 'btn btn-primary' %>
      <%= link_to t('doorkeeper.applications.buttons.cancel'), oauth_applications_path, class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/doorkeeper/applications/edit.html.erb
<div class="border-bottom mb-4">
  <h1><%= t('.title') %></h1>
</div>

<%= render 'form', application: @application %>

app/views/doorkeeper/applications/index.html.erb
<div class="border-bottom mb-4">
  <h1><%= t('.title') %></h1>
</div>

<p><%= link_to t('.new'), new_oauth_application_path, class: 'btn btn-success' %></p>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= t('.name') %></th>
    <th><%= t('.callback_url') %></th>
    <th><%= t('.confidential') %></th>
    <th><%= t('.actions') %></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @applications.each do |application| %>
    <tr id="application_<%= application.id %>">
      <td class="align-middle">
        <%= link_to application.name, oauth_application_path(application) %>
      </td>
      <td class="align-middle">
        <%= simple_format(application.redirect_uri) %>
      </td>
      <td class="align-middle">
        <%= application.confidential? ? t('doorkeeper.applications.index.confidentiality.yes') : t('doorkeeper.applications.index.confidentiality.no') %>
      </td>
      <td class="align-middle">
        <%= link_to t('doorkeeper.applications.buttons.edit'), edit_oauth_application_path(application), class: 'btn btn-link' %>
      </td>
      <td class="align-middle">
        <%= render 'delete_form', application: application %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/doorkeeper/applications/new.html.erb
<div class="border-bottom mb-4">
  <h1><%= t('.title') %></h1>
</div>

<%= render 'form', application: @application %>

app/views/doorkeeper/applications/show.html.erb
<div class="border-bottom mb-4">
  <h1><%= t('.title', name: @application.name) %></h1>
</div>

<div class="row">
  <div class="col-md-8">
    <h4><%= t('.application_id') %>:</h4>
    <p><code class="bg-light" id="application_id"><%= @application.uid %></code></p>

    <h4><%= t('.secret') %>:</h4>
    <p><code class="bg-light" id="secret"><%= @application.secret %></code></p>

    <h4><%= t('.scopes') %>:</h4>
    <p><code class="bg-light" id="scopes"><%= @application.scopes.presence || raw('&nbsp;') %></code></p>

    <h4><%= t('.confidential') %>:</h4>
    <p><code class="bg-light" id="confidential"><%= @application.confidential? %></code></p>

    <h4><%= t('.callback_urls') %>:</h4>

    <table>
      <% @application.redirect_uri.split.each do |uri| %>
        <tr>
          <td>
            <code class="bg-light"><%= uri %></code>
          </td>
          <td>
            <%= link_to t('doorkeeper.applications.buttons.authorize'), oauth_authorization_path(client_id: @application.uid, redirect_uri: uri, response_type: 'code', scope: @application.scopes), class: 'btn btn-success', target: '_blank' %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="col-md-4">
    <h3><%= t('.actions') %></h3>

    <p><%= link_to t('doorkeeper.applications.buttons.edit'), edit_oauth_application_path(@application), class: 'btn btn-primary' %></p>

    <p><%= render 'delete_form', application: @application, submit_btn_css: 'btn btn-danger' %></p>
  </div>
</div>

app/views/doorkeeper/authorizations/error.html.erb
<div class="border-bottom mb-4">
  <h1><%= t('doorkeeper.authorizations.error.title') %></h1>
</div>

<main role="main">
  <pre><%= @pre_auth.error_response.body[:error_description] %></pre>
</main>

app/views/doorkeeper/authorizations/new.html.erb
<header class="page-header" role="banner">
  <h1><%= t('.title') %></h1>
</header>

<main role="main">
  <p class="h4">
    <%= raw t('.prompt', client_name: content_tag(:strong, class: 'text-info') { @pre_auth.client.name }) %>
  </p>

  <% if @pre_auth.scopes.count > 0 %>
    <div id="oauth-permissions">
      <p><%= t('.able_to') %>:</p>

      <ul class="text-info">
        <% @pre_auth.scopes.each do |scope| %>
          <li><%= t scope, scope: [:doorkeeper, :scopes] %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form_tag oauth_authorization_path, method: :post do %>
      <%= hidden_field_tag :client_id, @pre_auth.client.uid %>
      <%= hidden_field_tag :redirect_uri, @pre_auth.redirect_uri %>
      <%= hidden_field_tag :state, @pre_auth.state %>
      <%= hidden_field_tag :response_type, @pre_auth.response_type %>
      <%= hidden_field_tag :scope, @pre_auth.scope %>
      <%= hidden_field_tag :code_challenge, @pre_auth.code_challenge %>
      <%= hidden_field_tag :code_challenge_method, @pre_auth.code_challenge_method %>
      <%= submit_tag t('doorkeeper.authorizations.buttons.authorize'), class: "btn btn-success btn-lg btn-block" %>
    <% end %>
    <%= form_tag oauth_authorization_path, method: :delete do %>
      <%= hidden_field_tag :client_id, @pre_auth.client.uid %>
      <%= hidden_field_tag :redirect_uri, @pre_auth.redirect_uri %>
      <%= hidden_field_tag :state, @pre_auth.state %>
      <%= hidden_field_tag :response_type, @pre_auth.response_type %>
      <%= hidden_field_tag :scope, @pre_auth.scope %>
      <%= hidden_field_tag :code_challenge, @pre_auth.code_challenge %>
      <%= hidden_field_tag :code_challenge_method, @pre_auth.code_challenge_method %>
      <%= submit_tag t('doorkeeper.authorizations.buttons.deny'), class: "btn btn-danger btn-lg btn-block" %>
    <% end %>
  </div>
</main>

app/views/doorkeeper/authorizations/show.html.erb
<header class="page-header">
  <h1><%= t('.title') %>:</h1>
</header>

<main role="main">
  <code id="authorization_code"><%= params[:code] %></code>
</main>

app/views/doorkeeper/authorized_applications/_delete_form.html.erb
<%- submit_btn_css ||= 'btn btn-link' %>
<%= form_tag oauth_authorized_application_path(application), method: :delete do %>
  <%= submit_tag t('doorkeeper.authorized_applications.buttons.revoke'), onclick: "return confirm('#{ t('doorkeeper.authorized_applications.confirmations.revoke') }')", class: submit_btn_css %>
<% end %>

app/views/doorkeeper/authorized_applications/index.html.erb
<header class="page-header">
  <h1><%= t('doorkeeper.authorized_applications.index.title') %></h1>
</header>

<main role="main">
  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= t('doorkeeper.authorized_applications.index.application') %></th>
      <th><%= t('doorkeeper.authorized_applications.index.created_at') %></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.name %></td>
        <td><%= application.created_at.strftime(t('doorkeeper.authorized_applications.index.date_format')) %></td>
        <td><%= render 'delete_form', application: application %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Oauth2 Login</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'react_fe/assets/stylesheets/app' %>
    <!---
    <script src="https://cdn.logrocket.io/LogRocket.min.js" crossorigin="anonymous"></script>
    <script>window.LogRocket && window.LogRocket.init('u0ne2v/oes');</script>
    -->
  </head>

  <body>
    <noscript>
      You need to enable JavaScript to run this app.
    </noscript>
  
    <%= yield %>
    
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'react_fe/index' %>
  </body>
</html>

app/views/layouts/doorkeeper/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Amministrazione Applicazioni</title>
  <%= stylesheet_link_tag "doorkeeper/admin/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
  <%= link_to t('doorkeeper.layouts.admin.nav.oauth2_provider'), oauth_applications_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if request.path == oauth_applications_path %>">
        <%= link_to t('doorkeeper.layouts.admin.nav.applications'), oauth_applications_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('doorkeeper.layouts.admin.nav.home'), "https://start.soluzionipa.it/auth_hub/sa", class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

<div class="doorkeeper-admin container">
  <%- if flash[:notice].present? %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
  <% end -%>

  <%= yield %>
</div>
</body>
</html>

app/views/layouts/doorkeeper/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oauth2 Login</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  
  
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <%- if flash[:notice].present? %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
  <% end -%>

  <%= yield %>
</div>
</body>
</html>